app:
  title : Snoopy stress test application
  version : 1.0.0

datasource:
  url: jdbc:mariadb://deogicorgi.home:3306/snoopy
  username: deogicorgi
  password: 8813
  maximum-pool-size : 30

spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: ture

#logging:
#  level:
#    org.hibernate.SQL: debug
