application:
  title : Snoopy stress test application
  version : 1.0.0

spring:
  datasource:
    url: jdbc:mariadb://deogicorgi.home:3306/snoopy
    driver-class-name: org.mariadb.jdbc.Driver
    username: deogicorgi
    password: 8813
