app:
  title : Snoopy stress test application
  version : 1.0.0

datasource:
  url: jdbc:mariadb://deogicorgi.home:3306/snoopy
  username: deogicorgi
  password: 8813
  maximum-pool-size : 30

spring:
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: ture
        show_sql: true

#
#logging:
#  level:
#    org.hibernate.SQL: debug
