app:
  title : Snoopy stress test application
  version : 1.0.0
spring:
  datasource:
    url: jdbc:mariadb://deogicorgi.home:3306/snoopy
    username: deogicorgi
    password: 8813
    hikari:
      maximum-pool-size : 30
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: ture

#logging:
#  level:
#    org.hibernate.SQL: debug
#    com:
#      zaxxer:
#        hikari: debug
